### PR TITLE
Pin22GpioSignal() read gpio21

### PR DESCRIPTION
**Pull request by andcor**
Fixed a simple typo

### CODE REVIEW

**Comment by CoRfr** [comment]
Hi @andcor , thanks for providing this PR, looks like a legit issue.

Before we can accept this PR, did you sign the contributor agreement?
https://github.com/legatoproject/legato-af/blob/master/CONTRIB_INDIVIDUAL.md

Thanks

**Comment by andcor** [comment]
Just signed the contribution agrement. But my email bounces off legal@legato.io. Seems the address does not exist?

**Comment by achuang** [comment]
Hi @andcor, we did receive your signed contribution agreement. Thanks!

**Comment by CoRfr** [comment]
Merged as https://github.com/legatoproject/legato-af/commit/600caf53a9cd095a51f2b52c952c789d9a653516

Thanks!

**Pull request closed without merging**
